include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_typing_uninitialized_variables : false
    prefer_const_constructors_in_immutables : false
    prefer_const_constructors : false
    slash_for_doc_comments : false
    avoid_print : false
    prefer_const_literals_to_create_immutables : false
